### ISSUE TITLE
Vom Container zum Pod: Netzwerkprobleme im inneren Docker

### ISSUE THREAD

**Issue by AndyTM** [nicholasdille/heise-k8s-colg#1]
Hallo!
```
 docker run -it --network container:pod docker:stable
/ # apk add jd
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.12/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.12/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  jd (missing):
    required by: world[jd]
````
So sieht die Ausgabe aus,  wenn ich curl und jd hinzufügen will.
Google hat mir verraten, dass es hier evtl um ein Bridging-Problem geht.

```
951e2e0cdb20   docker:stable          "docker-entrypoint.s…"   3 minutes ago    Exited (1) 7 seconds ago                                 determined_lovelace
350f0ba7f68e   docker:stable-dind     "dockerd-entrypoint.…"   5 minutes ago    Up 5 minutes                                      dockerd

c57a854c4959   registry:2             "/entrypoint.sh /etc…"   25 hours ago     Up 5 minutes                                             registry
e564415b23b6   ubuntu                 "bash -c 'sleep infi…"   25 hours ago     Up 6 minutes                                             pod
````
Gibt es hier einen Lösungsweg?
Basis:
Ubuntu 20.04.2 LTS 
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2

Für eine Unterstützung wäre ich dankbar.
Die "temporäre Namensauflösung funktioniert übrigens auch in einem ubuntu von der Stange nicht. Und Ja, ichhabe dien dockerd-Container privileged gestartet.

**Comment by nicholasdille** [comment]
Hallo Andy!

Vielen Dank für die ausführliche Beschreibung. Auf den ersten Blick sieht es nach einem Typo aus. Ohne dass ich in die Folien bzw. Demo geschaut habe, muss es bestimmt `jq` heißen.

Kannst Du es bitte mal mit folgendem Befehl testen:

```
apk add jq
```

Ich schaue nachher mal in die Demo für das Kapitel! 

Viele Grüße 
Nicholas

**Comment by AndyTM** [comment]
> Hallo Andy!
> 
> Vielen Dank für die ausführliche Beschreibung. Auf den ersten Blick sieht es nach einem Typo aus. Ohne dass ich in die Folien bzw. Demo geschaut habe, muss es bestimmt `jq` heißen.
> 
> Kannst Du es bitte mal mit folgendem Befehl testen:
> 
> ```
> apk add jq
> ```
> 
> Ich schaue nachher mal in die Demo für das Kapitel!
> 
> Viele Grüße
> Nicholas

Hallo!
Vielen Dank für die schnelle Reaktion.
Nein das war nicht das Problem. (Danke für den Hinweis auf den Typo)
Äusserlich ist es ein temporäres Problem bei der Namensauflösung.
Einige Versuche z.b. mit einem standard ubuntu container hatten ein ähnliches Bild.
[ Hier ](https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host)
Habe ich dann aufgegeben.
Vermutlich eine Problem mit dem Bridging im docker-docker
Viele Grüße
Andy
P.S. snip1 der Ausschnitt aus dem Video an den ich mich gehalten habe
<img width="579" alt="snip1" src="https://user-images.githubusercontent.com/17992685/126910119-53105dfd-aff8-4c2f-99e3-23daf10e282b.PNG">

**Comment by nicholasdille** [comment]
Nachtrag: Das Problem mit der Namensauflösung erinnert mich an zwei Dinge:

1. Wenn Du WSL2 in einer älteren Version von Windows 10 verwendest, kann es sein, dass die Namensauflösung "plötzlich" kaputt geht: https://github.com/microsoft/WSL/issues/4285

1. Kürzlich habe ich selbst erlebt, dass DNS im Container nicht funktioniert, weil es unter Ubuntu irgendwie einen Konflikt mit `systemd-resolve` gab.

Hoffentlich hilft Dir das weiter!

**Comment by AndyTM** [comment]
Hi!
Zu 1: Nein. auf Grund von Komplikationen arbeite ich jetzt auf Blech. (auch wenn ich es bevorzugt hätte lokal im WSL zu abeiten)
Zu 2: Das klingt interessant. Kannst Du mir da mehr erzählen? Da könnte der Hund begraben sein
Danke
Andy

**Comment by nicholasdille** [comment]
Ich kann mich nur wage erinnern, dass ich die `/etc/resolv.conf` selbst angelegt habe. In neueren Ubuntu ist es ein Symlink auf die von `systemd-resolve` angelegte `resolv.conf`. Allerdings bin ich mir nicht mehr ganz sicher. Leider finde ich den entsprechenden Eintrag bei StackOverflow/ServerFault nicht mehr :-(

Du solltest erstmal in die Richtung recherchieren, bevor Du den Ansatz aus meiner Erinnerung testet!

**Comment by AndyTM** [comment]
Danke! ich bleib da dran. Wäre schade, wenn der Kurst hier schon scheitern würde. Für jeden Input wäre ich dankbar.

**Comment by nicholasdille** [comment]
Ich hoffe sehr, dass Du eine Lösung findest. Leider kann ich nicht sicherstellen, dass die Basis für den Kurs immer identisch konfiguriert ist und identisch funktioniert.

Es tut mir Leid, dass Du Schwierigkeiten mit Docker und DNS hast. Halte mich bitte auf dem Laufenden, wie Du mit dem Problem voran kommst. Vielleicht kann ich ja noch etwas beitragen.

**Comment by AndyTM** [comment]
Zwischenstand: Bereits im pod kommt es zu Problemen mit der Namesnauflösung. Die resolv.conf ist mit dem host identisch.
Mein Verdacht liegt hier auf falschen oder fehlenden iptables-regeln auf dem host.
Hier wäre ich für einen Tip dankbar.

**Comment by nicholasdille** [comment]
Schau bitte mal ins Log vom `dockerd` auf dem Host. Steht da was, dass er ein Problem mit iptables hätte? In neuen Distributionen wird nftables verwendet, wodurch Docker daran gehindert wird Regeln anzulegen. Wenn Du zu iptables legacy wechselst, könnte das helfen.

Anleitung: https://askubuntu.com/questions/1262629/on-new-linux-kernel-5-8rc7-in-ubuntu-20-docker-will-not-start, https://wiki.debian.org/nftables

Hintergrundwissen: https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables#the_kernel_api

**Comment by nicholasdille** [comment]
Hast Du das Problem mit Docker und DNS lösen können? Haben meine letzten Tipps geholfen?

**Comment by AndyTM** [comment]
Hallo!
Ja ich bin etwas weiter gekommen. Die Ursache war ein DNS-Konflikt (Bind / Systemd-resolved).

Nun suche ich nach einer Lösung wie ich den Systemd-Resolved in den Docker bekomme.
Zuletzt habe ich eine Anleitung gefunden neben dem resolved einen dnsmasq für das Dockerinterface zu installieren.

Hierbei muss man beachten, dass der dnsmasq nur auf die Interfaces / IPs von docker lauschen soll.
```
interface=docker0
listen-address=172.17.0.1
bind-interfaces
```
sonst kommt es zu Konflikten!
