### ISSUE TITLE
traefik-dashboard not startable

### ISSUE THREAD

**Issue by JLammering** [nicholasdille/heise-k8s-colg#10]
in 05/04 this [line](https://github.com/nicholasdille/heise-k8s-colg/blob/92b4e618be62a3c0c565878a82ce26b545562a47/05%20Dienste%20erreichbar%20machen/04%20Reverse%20Proxy%20als%20Zugangspunkt/traefik-dashboard.yaml#L3C7-L3C7) makes problems:
`error: resource mapping not found for name: "traefik-dashboard" namespace: "kube-system" from "STDIN": no matches for kind "Ingress" in version "extensions/v1beta1"
ensure CRDs are installed first`

I suppose the apiVersion should be changed but maybe more

**Comment by nicholasdille** [comment]
Danke, auch hier gab es Deprecations seit der Erstellung des Kurses
