### ISSUE TITLE
02 Kubernetes verwenden/04 Pods skalieren - Kein Tag 'latest' 

### ISSUE THREAD

**Issue by t0mschroeder** [nicholasdille/heise-k8s-colg#2]
Das Docker-Image nicholasdille/nginx-hello kann nicht heruntergeladen werden, da es kein Tag `latest` hat. 

[replicaset.yaml](https://github.com/nicholasdille/heise-k8s-colg/blob/cc3dc12bc5dce1b92410323837bf30cff4389e40/02%20Kubernetes%20verwenden/04%20Pods%20skalieren/replicaset.yaml) 

War ganz gut, weil ich mich gleich mit dem Debugging auseinandersetzen konnte und habe den Tag `1.19` hinzugefügt. ;-)

**Comment by nicholasdille** [comment]
Das ist natürlich peinlich. Sorry dafür und Glückwunsch dass Du es selbst gelöst hast 😀 Ich werde das korrigieren!

Danke nochmal, dass Du den Fehler gemeldet hast!

**Comment by nicholasdille** [comment]
Ich habe gerade das [Release 1.0.7](https://github.com/nicholasdille/heise-k8s-colg/releases/tag/1.0.7) veröffentlicht. Darin ist die `replicaset.yaml` korrigiert.
