### ISSUE TITLE
nicholasdille/nginx-hello nicht für arm verfügbar ...

### ISSUE THREAD

**Issue by rma4711** [nicholasdille/heise-k8s-colg#5]
ich gehe gerade die Reihe "Container-Orchestrierung mit Kubernetes leicht gemacht" durch und stolpere gerade darüber, dass das alle images nicholasdille/nginx-hello:* nur für amd64 verfügbar sind.

Auf meinen raspi's benötige ich aber aarch64 ...

Ist das Dokerfile und die SW für das 'nginx-hello' irgendwo verfügbar? Dann könnte ich mir möglicherweise das image selbst basteln ...

**Comment by nicholasdille** [comment]
Hallo, entschuldigung für die späte Antwort :-(

Die Quellen für alle Images befinden sich [hier](https://github.com/nicholasdille/heise-k8s-colg/tree/master/common/docker).

**Comment by nicholasdille** [comment]
Ich habe gerade `linux/arm64` für alle Images hinzugefügt.
