### ISSUE TITLE
Curl command does nothing

### ISSUE THREAD

**Issue by JLammering** [nicholasdille/heise-k8s-colg#6]
https://github.com/nicholasdille/heise-k8s-colg/blob/92b4e618be62a3c0c565878a82ce26b545562a47/03%20Kubernetes%20verstehen/06%20Authentifizierung%20am%20Cluster/auth.demo#L7

`curl --silent https://api.github.com/repos/mike-engel/jwt-cli/releases/latest | \
    jq --raw-output '.assets[] | select(.name | endswith("-linux.tar.gz")) | .browser_download_url' | \
    xargs curl --location --fail | \
    tar -xz --strip-components=2`

I don't know if I have a problem with my machine but his curl commadn does nothing and does not produce the jwt file like expected in the course. The rest of the course went well for me. Maybe the link is not up to date?

**Comment by nicholasdille** [comment]
Thanks for the feedback :-)

It looks like the maintainer has changed the contents of the release artifact... The correct command is now:

```bash
curl --silent https://api.github.com/repos/mike-engel/jwt-cli/releases/latest | \
    jq --raw-output '.assets[] | select(.name | endswith("-linux.tar.gz")) | .browser_download_url' | \
    xargs curl --location --fail | \
    tar -xz
```

I will update the repository!
