### ISSUE TITLE
cronjob not available with apiVersion batch/v1beta1

### ISSUE THREAD

**Issue by JLammering** [nicholasdille/heise-k8s-colg#7]
In Lecture 4/10 the cronjob is explained. The cronjob.yaml uses these lines
`apiVersion: batch/v1beta1
kind: CronJob`

This results in:
`error: resource mapping not found for name: "hello" namespace: "" from "cronjob.yaml": no matches for kind "CronJob" in version "batch/v1beta1"
ensure CRDs are installed first`

The solution is to change the apiVersion to _batch/v1_ as explained in [kubernetes update guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25)

**Comment by nicholasdille** [comment]
Vielen Dank für die Korrektur!
